[project]
name = "secretary"
version = "0.1.0"
description = "Todo List Manager"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.2.0",
]

[tool.uv.workspace]
members = ["secretary"]
